kind: ConfigMap
apiVersion: v1
metadata:
  name: nativehamqsc
  namespace: cp4i
data:
  nativehamqsc.mqsc: >-
    define ql(APPQ) DEFPSIST(YES)

    define ql(APPQ1) DEFPSIST(YES)

    DEFINE CHANNEL(EXTERNALCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP)
    SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')

    set chlauth(EXTERNALCHL) TYPE(BLOCKUSER) USERLIST(NOBODY)

    REFRESH SECURITY TYPE(CONNAUTH)