kind: Service
apiVersion: v1
metadata:
  name: kedamq-ibm-mq
  namespace: cp4i
spec:
  ports:
    - name: console-https
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: qmgr
      protocol: TCP
      port: 1414
      targetPort: 1414
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    statefulSetName: kedaqm