apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-ibmmq-trigger-auth
  namespace: cp4i
spec:
  secretTargetRef:
    - key: ADMIN_USER
      name: keda-ibmmq-secret
      parameter: username
    - key: ADMIN_PASSWORD
      name: keda-ibmmq-secret
      parameter: password
