kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: helloworldhpa
  namespace: cp4i
spec:
  scaleTargetRef:
    kind: IntegrationServer
    name: helloworld
    apiVersion: appconnect.ibm.com/v1beta1
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 20
