kind: Service
apiVersion: v1
metadata:
  name: unicluster-qm1-lb
  namespace: cp4i
spec:
  ports:
    - protocol: TCP
      port: 1414
      targetPort: 1414
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: unicluster-qm1
    app.kubernetes.io/name: ibm-mq